name: ci
on:
  pull_request:
  push:
    branches:
      - "**"
jobs:
  perl:
    name: "Perl ${{matrix.perl}}, Redis ${{matrix.redis}}"
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        perl: ["5.16", "5.26", "5.32"]
        redis: ["5", "latest"]
    runs-on: "${{matrix.os}}"
    steps:
      - uses: actions/checkout@v3
      - name: Setup redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: ${{ matrix.redis }}
          auto-start: true
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "${{matrix.perl}}"
          install-modules-with: cpanm
          install-modules-args: --with-develop --with-configure          
      - run: redis-cli --version
      - run: perl -V
      - name: Install dependencies
        run: |
          cpanm -n --installdeps .
          cpanm -n Test::CPAN::Changes Test::Pod::Coverage Test::Pod Test::Spelling
      - name: Run tests
        run: prove -l t
        env:
          HARNESS_OPTIONS: j4
          TEST_ONLINE: "redis://localhost:${{steps.setup.outputs.redis-port}}"
